/* ===========================================================================
    Hostile Goody Hut Rewards (HGHR) for Civilization VI
    Copyright © 2020-2025 yofabronecoforo
    All rights reserved.

    Begin ingame setup
=========================================================================== */

-- experience cap from killing barbarian units; default Value = 1
UPDATE GlobalParameters SET Value = 3 WHERE Name = 'EXPERIENCE_BARB_SOFT_CAP';

-- no experience from killing barbarian units at this level; default Value = 2
UPDATE GlobalParameters SET Value = 5 WHERE Name = 'EXPERIENCE_MAX_BARB_LEVEL';

-- experience earned from activating a goody hut; default Value = 10 (Pre XP2) | 8 (XP2 and beyond) [maybe now a hard 5 by default? fuck it]
UPDATE GlobalParameters SET Value = 3 WHERE Name = 'EXPERIENCE_ACTIVATE_GOODY_HUT';

-- 
REPLACE INTO Types
    (Type, Kind)
VALUES
    -- Hostile Villagers "rewards"
    ('GOODYHUT_HOSTILES', 'KIND_GOODY_HUT');

-- 
REPLACE INTO GoodyHuts
    (GoodyHutType, Weight)
VALUES
    -- Hostile Villagers "rewards"
    ('GOODYHUT_HOSTILES', 100);

-- new GoodyHutSubTypes
REPLACE INTO GoodyHutSubTypes
    (GoodyHut, SubTypeGoodyHut, Description, Weight, Turn, MinOneCity, RequiresUnit, ModifierID)
VALUES 
    -- ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RECON_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    -- ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RECON_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    -- ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RECON_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_MELEE_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_MELEE_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_MELEE_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RANGED_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RANGED_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_RANGED_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 0, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_ANTI_CAVALRY_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 2, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_ANTI_CAVALRY_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 2, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_ANTI_CAVALRY_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 2, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_HEAVY_CAVALRY_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 30, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_HEAVY_CAVALRY_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 30, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_HEAVY_CAVALRY_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 30, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_LIGHT_CAVALRY_1', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 55, 60, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_LIGHT_CAVALRY_2', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 30, 60, 0, 1, 'GOODY_HGHR_DUMMY_REWARD'), 
    ('GOODYHUT_HOSTILES', 'GOODYHUT_HOSTILE_LIGHT_CAVALRY_3', 'LOC_GOODYHUT_HOSTILES_DESCRIPTION', 15, 60, 0, 1, 'GOODY_HGHR_DUMMY_REWARD');

-- new Modifiers
REPLACE INTO Modifiers
    (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES
    -- dummy modifier - for use by rewards implemented via lua
    ('GOODY_HGHR_DUMMY_REWARD', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', 1, 1, NULL);
    
-- new ModifierArguments
REPLACE INTO ModifierArguments
    (ModifierId, Name, Value, Extra)
VALUES
    -- dummy modifier - for use by rewards implemented via lua
    ('GOODY_HGHR_DUMMY_REWARD', 'Amount', 0, NULL),
    ('GOODY_HGHR_DUMMY_REWARD', 'YieldType', 'YIELD_FOOD', NULL),
    ('GOODY_HGHR_DUMMY_REWARD', 'Scale', 0, NULL);

-- 
REPLACE INTO GoodyHutSubTypes_HGHR 
    (SubTypeGoodyHut, PromotionClass, NumUnits) 
VALUES 
    -- ('GOODYHUT_HOSTILE_RECON_1', 'PROMOTION_CLASS_RECON', 1), 
    -- ('GOODYHUT_HOSTILE_RECON_2', 'PROMOTION_CLASS_RECON', 2), 
    -- ('GOODYHUT_HOSTILE_RECON_3', 'PROMOTION_CLASS_RECON', 3), 
    ('GOODYHUT_HOSTILE_MELEE_1', 'PROMOTION_CLASS_MELEE', 1), 
    ('GOODYHUT_HOSTILE_MELEE_2', 'PROMOTION_CLASS_MELEE', 2), 
    ('GOODYHUT_HOSTILE_MELEE_3', 'PROMOTION_CLASS_MELEE', 3), 
    ('GOODYHUT_HOSTILE_RANGED_1', 'PROMOTION_CLASS_RANGED', 1), 
    ('GOODYHUT_HOSTILE_RANGED_2', 'PROMOTION_CLASS_RANGED', 2), 
    ('GOODYHUT_HOSTILE_RANGED_3', 'PROMOTION_CLASS_RANGED', 3), 
    ('GOODYHUT_HOSTILE_ANTI_CAVALRY_1', 'PROMOTION_CLASS_ANTI_CAVALRY', 1), 
    ('GOODYHUT_HOSTILE_ANTI_CAVALRY_2', 'PROMOTION_CLASS_ANTI_CAVALRY', 2), 
    ('GOODYHUT_HOSTILE_ANTI_CAVALRY_3', 'PROMOTION_CLASS_ANTI_CAVALRY', 3), 
    ('GOODYHUT_HOSTILE_HEAVY_CAVALRY_1', 'PROMOTION_CLASS_HEAVY_CAVALRY', 1), 
    ('GOODYHUT_HOSTILE_HEAVY_CAVALRY_2', 'PROMOTION_CLASS_HEAVY_CAVALRY', 2), 
    ('GOODYHUT_HOSTILE_HEAVY_CAVALRY_3', 'PROMOTION_CLASS_HEAVY_CAVALRY', 3), 
    ('GOODYHUT_HOSTILE_LIGHT_CAVALRY_1', 'PROMOTION_CLASS_LIGHT_CAVALRY', 1), 
    ('GOODYHUT_HOSTILE_LIGHT_CAVALRY_2', 'PROMOTION_CLASS_LIGHT_CAVALRY', 2), 
    ('GOODYHUT_HOSTILE_LIGHT_CAVALRY_3', 'PROMOTION_CLASS_LIGHT_CAVALRY', 3);

-- 
REPLACE INTO HostileVillagerUnits 
    (EraType, PromotionClass, UnitType) 
VALUES 
    -- ('ERA_ANCIENT', 'PROMOTION_CLASS_RECON', 'UNIT_SCOUT'), 
    ('ERA_ANCIENT', 'PROMOTION_CLASS_MELEE', 'UNIT_WARRIOR'), 
    ('ERA_ANCIENT', 'PROMOTION_CLASS_RANGED', 'UNIT_SLINGER'), 
    ('ERA_ANCIENT', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_SPEARMAN'), 
    ('ERA_ANCIENT', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_HEAVY_CHARIOT'), 
    ('ERA_ANCIENT', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HORSEMAN'), 
    -- ('ERA_CLASSICAL', 'PROMOTION_CLASS_RECON', 'UNIT_SCOUT'), 
    ('ERA_CLASSICAL', 'PROMOTION_CLASS_MELEE', 'UNIT_SWORDSMAN'), 
    ('ERA_CLASSICAL', 'PROMOTION_CLASS_RANGED', 'UNIT_ARCHER'), 
    ('ERA_CLASSICAL', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_SPEARMAN'), 
    ('ERA_CLASSICAL', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_HEAVY_CHARIOT'), 
    ('ERA_CLASSICAL', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HORSEMAN'), 
    -- ('ERA_MEDIEVAL', 'PROMOTION_CLASS_RECON', 'UNIT_SCOUT'), 
    ('ERA_MEDIEVAL', 'PROMOTION_CLASS_MELEE', 'UNIT_MAN_AT_ARMS'), 
    ('ERA_MEDIEVAL', 'PROMOTION_CLASS_RANGED', 'UNIT_CROSSBOWMAN'), 
    ('ERA_MEDIEVAL', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_PIKEMAN'), 
    ('ERA_MEDIEVAL', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_KNIGHT'), 
    ('ERA_MEDIEVAL', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HORSEMAN'), 
    -- ('ERA_RENAISSANCE', 'PROMOTION_CLASS_RECON', 'UNIT_SCOUT'), 
    ('ERA_RENAISSANCE', 'PROMOTION_CLASS_MELEE', 'UNIT_MUSKETMAN'), 
    ('ERA_RENAISSANCE', 'PROMOTION_CLASS_RANGED', 'UNIT_CROSSBOWMAN'), 
    ('ERA_RENAISSANCE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_PIKEMAN'), 
    ('ERA_RENAISSANCE', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_KNIGHT'), 
    ('ERA_RENAISSANCE', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HORSEMAN'), 
    -- ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_RECON', 'UNIT_RANGER'), 
    ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_MELEE', 'UNIT_LINE_INFANTRY'), 
    ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_RANGED', 'UNIT_FIELD_CANNON'), 
    ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_PIKEMAN'), 
    ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_KNIGHT'), 
    ('ERA_INDUSTRIAL', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_CAVALRY'), 
    -- ('ERA_MODERN', 'PROMOTION_CLASS_RECON', 'UNIT_RANGER'), 
    ('ERA_MODERN', 'PROMOTION_CLASS_MELEE', 'UNIT_INFANTRY'), 
    ('ERA_MODERN', 'PROMOTION_CLASS_RANGED', 'UNIT_FIELD_CANNON'), 
    ('ERA_MODERN', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_AT_CREW'), 
    ('ERA_MODERN', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_TANK'), 
    ('ERA_MODERN', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_CAVALRY'), 
    -- ('ERA_ATOMIC', 'PROMOTION_CLASS_RECON', 'UNIT_RANGER'), 
    ('ERA_ATOMIC', 'PROMOTION_CLASS_MELEE', 'UNIT_INFANTRY'), 
    ('ERA_ATOMIC', 'PROMOTION_CLASS_RANGED', 'UNIT_MACHINE_GUN'), 
    ('ERA_ATOMIC', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_AT_CREW'), 
    ('ERA_ATOMIC', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_TANK'), 
    ('ERA_ATOMIC', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HELICOPTER'), 
    -- ('ERA_INFORMATION', 'PROMOTION_CLASS_RECON', 'UNIT_RANGER'), 
    ('ERA_INFORMATION', 'PROMOTION_CLASS_MELEE', 'UNIT_MECHANIZED_INFANTRY'), 
    ('ERA_INFORMATION', 'PROMOTION_CLASS_RANGED', 'UNIT_MACHINE_GUN'), 
    ('ERA_INFORMATION', 'PROMOTION_CLASS_ANTI_CAVALRY', 'UNIT_MODERN_AT'), 
    ('ERA_INFORMATION', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'UNIT_MODERN_ARMOR'), 
    ('ERA_INFORMATION', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'UNIT_HELICOPTER');

-- unit rewards by game Era
-- REPLACE INTO UnitRewards
--     (Era, Recon, Melee, Ranged, AntiCavalry, HeavyCavalry, LightCavalry, Siege, Support, NavalMelee, NavalRanged)
-- VALUES
--     -- 
--     (0, 'UNIT_SCOUT', 'UNIT_WARRIOR', 'UNIT_SLINGER', 'UNIT_SPEARMAN', 'UNIT_HEAVY_CHARIOT', 'UNIT_HORSEMAN', 'UNIT_CATAPULT', 'UNIT_BATTERING_RAM', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
--     (1, 'UNIT_SCOUT', 'UNIT_SWORDSMAN', 'UNIT_ARCHER', 'UNIT_SPEARMAN', 'UNIT_HEAVY_CHARIOT', 'UNIT_HORSEMAN', 'UNIT_CATAPULT', 'UNIT_BATTERING_RAM', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
--     (2, 'UNIT_SCOUT', 'UNIT_MAN_AT_ARMS', 'UNIT_CROSSBOWMAN', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_HORSEMAN', 'UNIT_TREBUCHET', 'UNIT_SIEGE_TOWER', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
--     (3, 'UNIT_SCOUT', 'UNIT_MUSKETMAN', 'UNIT_CROSSBOWMAN', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_HORSEMAN', 'UNIT_BOMBARD', 'UNIT_SIEGE_TOWER', 'UNIT_CARAVEL', 'UNIT_FRIGATE'),
--     (4, 'UNIT_RANGER', 'UNIT_LINE_INFANTRY', 'UNIT_FIELD_CANNON', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_CAVALRY', 'UNIT_BOMBARD', 'UNIT_MEDIC', 'UNIT_IRONCLAD', 'UNIT_FRIGATE'),
--     (5, 'UNIT_RANGER', 'UNIT_INFANTRY', 'UNIT_FIELD_CANNON', 'UNIT_AT_CREW', 'UNIT_TANK', 'UNIT_CAVALRY', 'UNIT_ARTILLERY', 'UNIT_MEDIC', 'UNIT_IRONCLAD', 'UNIT_BATTLESHIP'),
--     (6, 'UNIT_RANGER', 'UNIT_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_AT_CREW', 'UNIT_TANK', 'UNIT_HELICOPTER', 'UNIT_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_BATTLESHIP'),
--     (7, 'UNIT_RANGER', 'UNIT_MECHANIZED_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_MODERN_AT', 'UNIT_MODERN_ARMOR', 'UNIT_HELICOPTER', 'UNIT_ROCKET_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_MISSILE_CRUISER'),
--     (8, 'UNIT_RANGER', 'UNIT_MECHANIZED_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_MODERN_AT', 'UNIT_MODERN_ARMOR', 'UNIT_HELICOPTER', 'UNIT_ROCKET_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_MISSILE_CRUISER');

/* ===========================================================================
    End ingame setup
=========================================================================== */
